### ISSUE TITLE
Different versions

### ISSUE THREAD

**Issue by dotlambda** [Blockstream/satellite#113]
Why do the versions on [PyPI](https://pypi.org/project/blocksat-cli/#history) and in the [changelog](https://github.com/Blockstream/satellite/blob/master/CHANGELOG.md) start with a zero, e.g. 0.4.7, but the [tags](https://github.com/Blockstream/satellite/tags) start with a 2, e.g. 2.4.7?

**Comment by blockstreamsatellite** [comment]
Hi @dotlambda ,

This discrepancy in the versioning has been in the code base since the transition to what was called **Blockstream Satellite 2.0** in 2020. The Python package and the corresponding PyPI package have been versioned as `0.x.y` since then, but the tags have been `2.x.y` because the tags from before Satellite 2.0 were numbered `1.x.y`. In contrast, the Python package did not exist when Satellite 1.0 was used, so it ended up starting from scratch (and versioned `0.x.y`) with Satellite 2.0.

This is only the history of the code base for your understanding. We plan on bumping the Python package major version from 0 to 2 to make the tags consistent with the package version in future releases.

Please let us know if you have any problems downloading or installing these.

Regards
