### ISSUE TITLE
Add more averages to terminal output

### ISSUE THREAD

**Issue by gmaxwell** [Blockstream/satellite#25]
The 1s terminal output is good-- I can tee it to a file and then graph it, but it would be nice if it had more averages esp because averaging dB values correctly is a PITA from a shell script and because the figures that come out right now are really noisy... so they're less useful for fine tuning pointing because their variance dwarfs small adjustments.

I think giving averages for all data in a number of windows would make sense:  1s window, 10sec window, 1 minute window, 10minute window,  and a long running exponentially weighed moving average with a 3dB weight fall off of an hour or so would be useful.

Windowed values are useful because older values outside of the window are disregarded completely...  You wouldn't want to use something like an 1m EWMA because if I had just disconnected the cable 1.5 minutes ago that figure is going to keep improving over the next several minutes which is really not at all informative.  Buffering 600 1s values to track a 10m window should be no biggie.   An EWMA is fine for the really long term output... 

Something like

```
---------------------------------1s---------10s---------1m----------10m--------long-- 
[2019-01-07 23:57:11]  MER dB  12.2716  /  12.2716  /  12.2716  /  12.2716  /  12.2716
[2019-01-07 23:57:11]  CRC Err 3.61E-05 /  3.61E-05 /  3.61E-05 /  3.61E-05 /  3.61E-05
[2019-01-07 23:57:11]  Worst 1s MER dB     12.2716  /  12.2716  /  12.2716
[2019-01-07 23:57:11]  FLL: Locked Offset: 0.8554 kHz Timing: Strong
```

I haven't personally found the text bar graph useful at all... maybe if it was on a less noisy data source and printed bigger so you could see it from a few feet away).

**Comment by gmaxwell** [comment]
Here is what I mean by it being noisy, these are the current 'SNR' outputs for me on a running setup with no adjustments being made: ![MER chart](https://people.xiph.org/~greg/temp/merdb.png)

As you can see, a change of even 0.5dB would be almost completely invisible in the second to second variations of this output.

**Comment by blockstreamsatellite** [comment]
@gmaxwell many thanks for the suggestions. We agree this is a good feature and we have added that to the list.

In the meantime, just so you know how this works today and so that you can better configure your receiver, please find some information next.

First of all, the MER measurement is implemented within a block that composes the `gr-blocksat` OOT module. Hence, it is kept at the `gr-blocksat` repo, which is a submodule of this (the `satellite`) repo. See the file at [gr-blocksat/lib/mer_measurement_impl.cc](https://github.com/Blockstream/gr-blocksat/blob/master/lib/mer_measurement_impl.cc).

Due to the way that this MER measurement block is connected in the receiver flowgraph, it operates with an input stream that is sampled at the symbol rate. Namely, it receives 156.25 ksymbols/sec. The result in the output of the block is the moving sample average of the decision-aided MER, which also provides an output in the same rate. That is, for every sample in, there is a new average MER value out.

The length of the moving averaging window is configurable as a parameter of the block, see [gr-blocksat/grc/blocksat_mer_measurement.xml#L15](https://github.com/Blockstream/gr-blocksat/blob/master/grc/blocksat_mer_measurement.xml#L15). As you correctly pointed out, this length is indeed set to 1024 symbols. This is something that is set at the instance(s) of the block in the receiver flowgraphs, so is something that depends on the `.grc` files in this `satellite` repository. See for example the case of `blocksat_rx_gui`, where the lengths for the two MER instances are set at [grc/blocksat_rx_gui.grc#L2679](https://github.com/Blockstream/satellite/blob/master/grc/blocksat_rx_gui.grc#L2679) and [blocksat_rx_gui.grc#L2726](https://github.com/Blockstream/satellite/blob/master/grc/blocksat_rx_gui.grc#L2726), respectively. In case of interest, you could change the parameter for these two instances, re-compile and try them out.

There was no specific reason originally to pick a window length of 1024 samples. It was simply a good tradeoff between the resulting variance in the output and the amount of memory consumed by the block. We can definitely make this configurable via command-line argument in the future and also provide different averaging lengths within the console prints, as you suggested. 

Regarding fluctuations, you are right of course. They indeed oscillate significantly and can impact the resolution of the observable MER improvement. On the other hand, there is a tradeoff with respect to the responsiveness of the measurement. As the antenna is being aimed, ideally the MER would respond quickly enough to allow immediate notion as to whether the new position is better or not. I think your suggestion of having different averaging durations is really suitable to allow visualisation of MER changes at both short and long term. Also, we can do that without using much memory, since we don't really need 156.25 ksymbols/sec to compute the MER. We can downsample the symbol stream and operate on a much lower rate stream. There is a block in GR called `keep 1 in N` that can be used for that.

Also, to confirm, the periodicity of the console prints are unrelated to the periodicity of the actual measurements. The console prints are all handled by another `gr-blocksat` block called `Rx Logger`, see [gr-blocksat/python/rx_logger.py](https://github.com/Blockstream/gr-blocksat/blob/master/python/rx_logger.py). This `Rx Logger` block gets a pointer to all other blocks of interest, so that it can call "getters" from the other blocks and with that fetch the metrics of interest. In the meantime, the other blocks are operating normally on their individual sample rates. So, in the case of the MER measurement, while the MER measurement block computes MER based on 156.25 samples per second, the `Rx Logger` checks the MER once a second and prints to the console. More importantly, because the `Rx Logger` is the one printing, it can coordinate the prints from different blocks and better organize how they look in the console. For example, the Rx apps are configured to print the MER once a second and the other stats once every 10 seconds. However, this is configurable and you could easily change that in the `.grc` file. For example, see the MER print period at [grc/blocksat_rx_gui.grc#L1089](https://github.com/Blockstream/satellite/blob/master/grc/blocksat_rx_gui.grc#L1089).

Lastly, on side-note, worth to point out also that the reason why this MER computation is said to be *decision-aided* is because it is taken after estimating the most likely constellation symbol (what corresponds to a *decision*). The block estimates the ideal symbol and then computing the error w.r.t. the actual received symbol. See for example the slicing function in [gr-blocksat/lib/mer_measurement_impl.cc#L137](https://github.com/Blockstream/gr-blocksat/blob/master/lib/mer_measurement_impl.cc#L137). Although this provides a useful MER computation, it is definitely not better than computing the MER with known data, since the decisions could be wrong. We can improve that by measuring MER solely during the preamble of the PHY frame, where the symbols are known (and hence the receiver doesn't have to make a decision). However, that' is something that is also on the future work list.

Please do feel free to ask or suggest further.

**Comment by blockstreamsatellite** [comment]
Hi @gmaxwell , we are closing this issue now that we changed from GNU Radio software to other platforms.
