### ISSUE TITLE
Fedora 31 Binary Package Error

### ISSUE THREAD

**Issue by Andreas237** [Blockstream/satellite#41]
Hi team,
Fresh Fedora 31 and just updated running on bare metal.

**System details:**
```
[root@localhost-live liveuser]# uname -a
Linux localhost-live 5.3.7-301.fc31.x86_64 #1 SMP Mon Oct 21 19:18:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Error:**
```
[root@localhost-live liveuser]# dnf copr enable blockstream/satellite

You are about to enable a Copr repository. Please note that this
repository is not part of the main distribution, and quality may vary.
...

Do you really want to enable copr.fedorainfracloud.org/blockstream/satellite? [y/N]: y
Error: This repository does not have any builds yet so you cannot enable it now.

```

I had the exact same issue using a Fedora 28 VM, fully updated as well.

**Comment by blockstreamsatellite** [comment]
Hi @Andreas237 ,

Thanks for opening the issue. Indeed there were previously no builds for Fedora 31. Originally we only shipped binaries for Fedora 27 and 28. However, these Fedora versions have reached [end-of-life](https://fedoraproject.org/wiki/End_of_life) since some time now, and so Copr is not maintaining packages for them anymore.

We've just made binaries available for Fedora 30 and Fedora 31. Unfortunately,  the `gnuradio` binaries of Fedora 30 and 31 (version 3.7.13) do not contain the `gr-qtgui` in-tree module that we use on `blocksat-rx-gui` and other GUI-based flow graphs. Consequently, the binaries that are now available for fc30 and fc31 only include the non-GUI flowgraphs (i.e. it includes `blocksat-rx`, but does not include `blocksat-rx-gui`). 

If you have flexibility, Ubuntu 18.04 should be a better distribution/series to work with our binary packages. The binary package there includes all GUI flowgraphs. Alternatively, you can always build from source. In the case of Fedora 30/31, however, you would need to build GNU Radio from source too in order to obtain the GUI tools, which can be time-consuming.

Hope this helps.
