### ISSUE TITLE
Why does blocksat-cli deps tbs-drivers change the network connections of the VM?

### ISSUE THREAD

**Issue by VDelport** [Blockstream/satellite#60]
I am trying to install blocksat-cli usb on a VM (Virtual Box) and the guest system Ubuntu.

While I am running blocksat-cli deps tbs-drivers the internet connection is available:

ip a
1: lo: <LOOPBACK, UP, LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link / loopback 00: 00: 00: 00: 00: 00 brd 00: 00: 00: 00: 00: 00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 :: 1/128 scope host
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST, MULTICAST, UP, LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link / ether 08: 00: 27: 04: 4a: 12 brd ff: ff: ff: ff: ff: ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic noprefix route enp0s3
       valid_lft 79378sec preferred_lft 79378sec
    inet6 fe80 :: d568: 4713: ac0d: 2994/64 scope link noprefix route
       valid_lft forever preferred_lft forever
3: dvb0_0: <BROADCAST, MULTICAST, NOARP, UP, LOWER_UP> mtu 4096 qdisc fq_codel state UNKNOWN group default qlen 1000
    link / ether 00: 22: ab: c0: 57: b0 brd ff: ff: ff: ff: ff: ff
4: dvb0_1: <BROADCAST, MULTICAST, NOARP, UP, LOWER_UP> mtu 4096 qdisc fq_codel state UNKNOWN group default qlen 1000
    link / ether 00: 22: ab: c0: 57: b0 brd ff: ff: ff: ff: ff: ff

After the blocksat-cli deps tbs-drivers and reboot I can connect to the TBS5927, but an internet connection is no longer possible:

ip a
1: lo: <LOOPBACK, UP, LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link / loopback 00: 00: 00: 00: 00: 00 brd 00: 00: 00: 00: 00: 00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 :: 1/128 scope host
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST, MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link / ether 08: 00: 27: 04: 4a: 12 brd ff: ff: ff: ff: ff: ff

Why does blocksat-cli deps tbs-drivers change the network connections?

**Comment by blockstreamsatellite** [comment]
Hi @VDelport ,

Command `blocksat-cli deps tbs-drivers` does not change the network connections. Perhaps you lost the connection simply due to rebooting?

In any case, the subcommands of `blocksat-cli deps` support dry-run mode, through which you can see all the shell commands that are executed without actually executing them. For the TBS drivers, you can check:

```
blocksat-cli deps --dry tbs-drivers
```

In contrast to the TBS driver installation step, note that command `blocksat-cli usb config` does create new network interfaces for the DVB-S2 adapters. On Ubuntu 18.04+, the CLI creates network interfaces with static IP addresses using [Netplan](https://netplan.io/). However, the CLI does not remove any existing network interface or connection.

Again, you can check all the steps that are executed without actually executing them. This is actually the default on command `usb cfg` when executed by a non-root user. Assuming that's your case, just run it like so:
```
blocksat-cli usb cfg
```
If the changes work for you and you want to apply them, you can simply run as root (i.e., with `sudo`, as given below). If not, you can adapt the steps and run them manually.
```
sudo blocksat-cli usb cfg
```
